# Generated by Django 4.2.3 on 2023-08-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='profesion',
        ),
    ]
